language: java
sudo: true 
deploy:
   edge: true
   provider: cloudfoundry
   username: bhaskarprofs@gmail.com
   password: 242637aa
   api: https://api.run.pivotal.io
   organization: Timesheet
   space: development
